
all:
	gcc client.c -o client
	gcc server_1.c -o server-1
	gcc server_2.c -o server-2
	gcc server_3.c -o server-3
	gcc prow_client.c -o prow_client
	gcc prow_server.c -o prow_server

clean:
	rm client server-1 server-2 server-3 prow_client prow_server

